version: "3.7"
services:
  rabbitmq-flask:
    hostname: rabbit-flask
    container_name: rabbit-flask
    image: 'rabbitmq:3.8-management-alpine'
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=idoT
      - RABBITMQ_DEFAULT_PASS=JellyBeans
    volumes:
      - rabbitmq_log:/var/log/rabbitmq
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  postgres-flask:
    hostname: postgres-flask
    container_name: postgres-flask
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=ShrimpCalzone
      - POSTGRES_USER=idoT
      - POSTGRES_DB=PostgresDB

  worker:
    container_name: rabbit-flask-worker
    build: './worker'
    env_file:
      - ./worker/.env
    volumes:
    - ./worker:/worker
    depends_on:
      - server

  server:
    container_name: rabbit-flask-server
    build: './server'
    volumes:
    - ./server:/flask_app
    env_file:
      - ./server/.env
    ports:
    - 5000:5000
    depends_on:
      - rabbitmq-flask
      - postgres-flask

volumes:
  rabbitmq_log:
  rabbitmq_data: